# spring.application.name=cashcove
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

server.servlet.context-path=/api/v1.0

#JPA configurations

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties..hibernate.format_sql=true

#Email configurations
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${MAIL_SMTP_FROM}

jwt.secret.key=${JWT_SECRET_KEY}

cashcove.frontend.url=${FRONTEND_URL}


ratelimit.login.ip.capacity=50
ratelimit.login.ip.refillSeconds=7200
ratelimit.login.user.capacity=3
ratelimit.login.user.refillSeconds=900
ratelimit.isauth.user.capacity=5
ratelimit.isauth.user.refillSeconds=600
ratelimit.isauth.ip.capacity=20
ratelimit.isauth.ip.refillSeconds=1800